### ISSUE TITLE
registeryAsync err

### ISSUE THREAD

**Issue by alexlamsl** [Daplie/letiny-core#5] opened 2016-05-11 15:14 UTC
My site uses `letsencrypt-express` without any troubles with the certificate or access, except for this popping up every now and then in the logs:
```
[DEBUG le/lib/core.js] registeryAsync err
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:138:11)
    at new Buffer (buffer.js:65:10)
    at b64ToBinstr (letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:16:10)
    at toForgePrivateKey (letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:45:5)
    at Object.privateJwkToPems (letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:91:12)
    at Object.tryCatcher (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:16:23)
    at Object.ret [as privateJwkToPemsAsync] (eval at <anonymous> (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at letsencrypt-express/node_modules/letsencrypt/lib/accounts.js:109:21
    at tryCatcher (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:628:18)
    at PromiseArray._resolve (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:564:26)
    at Promise._settlePromise0 (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:514:17)
```

**Comment by coolaj86** [comment] 2016-08-01 05:51
Duplicate of https://github.com/Daplie/node-letsencrypt/issues/23

Will be fixing with https://github.com/Daplie/rsa-compat.js/issues/2

**Closed by coolaj86** 2016-08-01 05:51 UTC
